"""added foreign key for author in messages

Revision ID: 3b0f6684e9e6
Revises: 7fcda04c5efb
Create Date: 2025-07-26 17:35:14.612991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0f6684e9e6'
down_revision = '7fcda04c5efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key("author_key", 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint("author_key", type_='foreignkey')

    # ### end Alembic commands ###
