"""Added text, time and date for messages

Revision ID: 7a5bf6db2f1c
Revises: 4e698653d8c4
Create Date: 2025-07-23 12:15:33.266148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5bf6db2f1c'
down_revision = '4e698653d8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('text', sa.String(length=500), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('text')
        batch_op.drop_column('author_id')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
