"""Added active users table

Revision ID: 8171c0f1262f
Revises: e8f0a53a3ea2
Create Date: 2025-07-24 21:50:27.017979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8171c0f1262f'
down_revision = 'e8f0a53a3ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_users')
    # ### end Alembic commands ###
