"""added author to text table

Revision ID: e8f0a53a3ea2
Revises: 7a5bf6db2f1c
Create Date: 2025-07-23 12:36:29.263022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f0a53a3ea2'
down_revision = '7a5bf6db2f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key("author_id_link", 'user', ['text'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('text',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
